In [1]:
import pandas as pd

data = {
    "Year": [2018, 2017, 2016, 2019, 2020, 2015, 2014, 2021, 2013, 2022,
             2018, 2019, 2016, 2017, 2020, 2021, 2015, 2014, 2022, 2018],

    "Present_Price": [8.5, 6.2, 9.1, 12.5, 15.0, 5.4, 4.9, 18.2, 3.8, 22.0,
                      10.5, 11.8, 7.6, 6.9, 14.2, 19.5, 5.8, 4.5, 23.0, 9.8],

    "Kms_Driven": [25000, 35000, 42000, 18000, 12000, 50000, 60000, 8000, 70000, 5000,
                   22000, 19000, 40000, 33000, 15000, 9000, 47000, 62000, 4000, 28000],

    "Fuel_Type": [
        "Petrol", "Diesel", "Petrol", "Diesel", "Petrol",
        "Petrol", "Diesel", "Petrol", "Petrol", "Diesel",
        "Diesel", "Petrol", "Diesel", "Petrol", "Diesel",
        "Petrol", "Petrol", "Diesel", "Petrol", "Diesel"
    ],

    "Seller_Type": [
        "Dealer", "Dealer", "Individual", "Dealer", "Dealer",
        "Individual", "Dealer", "Dealer", "Individual", "Dealer",
        "Dealer", "Individual", "Dealer", "Dealer", "Individual",
        "Dealer", "Individual", "Dealer", "Dealer", "Individual"
    ],

    "Transmission": [
        "Manual", "Manual", "Manual", "Automatic", "Automatic",
        "Manual", "Manual", "Automatic", "Manual", "Automatic",
        "Manual", "Automatic", "Manual", "Manual", "Automatic",
        "Automatic", "Manual", "Manual", "Automatic", "Manual"
    ],

    "Owner": [0,0,1,0,0,1,2,0,2,0,1,0,1,0,0,0,2,1,0,1],

    "Selling_Price": [
        7.8,5.4,6.5,11.2,13.8,
        4.2,3.8,16.5,2.7,20.5,
        9.1,10.3,6.2,5.9,13.2,
        17.8,4.5,3.5,21.4,8.6
    ]
}

In [2]:
df = pd.DataFrame(data)

In [4]:
df.head()

,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Selling_Price
0,2018,8.5,25000,Petrol,Dealer,Manual,0,7.8
1,2017,6.2,35000,Diesel,Dealer,Manual,0,5.4
2,2016,9.1,42000,Petrol,Individual,Manual,1,6.5
3,2019,12.5,18000,Diesel,Dealer,Automatic,0,11.2
4,2020,15.0,12000,Petrol,Dealer,Automatic,0,13.8

In [3]:
df.tail()

,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Selling_Price
15,2021,19.5,9000,Petrol,Dealer,Automatic,0,17.8
16,2015,5.8,47000,Petrol,Individual,Manual,2,4.5
17,2014,4.5,62000,Diesel,Dealer,Manual,1,3.5
18,2022,23.0,4000,Petrol,Dealer,Automatic,0,21.4
19,2018,9.8,28000,Diesel,Individual,Manual,1,8.6

In [5]:
df.shape

(20, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           20 non-null     int64
 1   Present_Price  20 non-null     float64
 2   Kms_Driven     20 non-null     int64
 3   Fuel_Type      20 non-null     object
 4   Seller_Type    20 non-null     object
 5   Transmission   20 non-null     object
 6   Owner          20 non-null     int64
 7   Selling_Price  20 non-null     float64
dtypes: float64(2), int64(3), object(3)
memory usage: 1.4+ KB

In [7]:
df.describe()

              Year  Present_Price    Kms_Driven      Owner  Selling_Price
count    20.000000      20.000000     20.000000  20.000000       20.00000
mean   2017.750000      10.960000  30200.000000   0.600000        9.64500
std       2.750598       5.942036  20030.503055   0.753937        5.79078
min    2013.000000       3.800000   4000.000000   0.000000        2.70000
25%    2015.750000       6.100000  14250.000000   0.000000        5.17500
50%    2018.000000       9.450000  26500.000000   0.000000        8.20000
75%    2020.000000      14.400000  43250.000000   1.000000       13.35000
max    2022.000000      23.000000  70000.000000   2.000000       21.40000

In [9]:
df.isnull().sum()

Year             0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
Selling_Price    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [10]:
print(df)

    Year  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner  \
0   2018            8.5       25000    Petrol      Dealer       Manual      0
1   2017            6.2       35000    Diesel      Dealer       Manual      0
2   2016            9.1       42000    Petrol  Individual       Manual      1
3   2019           12.5       18000    Diesel      Dealer    Automatic      0
4   2020           15.0       12000    Petrol      Dealer    Automatic      0
5   2015            5.4       50000    Petrol  Individual       Manual      1
6   2014            4.9       60000    Diesel      Dealer       Manual      2
7   2021           18.2        8000    Petrol      Dealer    Automatic      0
8   2013            3.8       70000    Petrol  Individual       Manual      2
9   2022           22.0        5000    Diesel      Dealer    Automatic      0
10  2018           10.5       22000    Diesel      Dealer       Manual      1
11  2019           11.8       19000    Petrol  Individual    Automatic      0
12  2016            7.6       40000    Diesel      Dealer       Manual      1
13  2017            6.9       33000    Petrol      Dealer       Manual      0
14  2020           14.2       15000    Diesel  Individual    Automatic      0
15  2021           19.5        9000    Petrol      Dealer    Automatic      0
16  2015            5.8       47000    Petrol  Individual       Manual      2
17  2014            4.5       62000    Diesel      Dealer       Manual      1
18  2022           23.0        4000    Petrol      Dealer    Automatic      0
19  2018            9.8       28000    Diesel  Individual       Manual      1

    Selling_Price
0             7.8
1             5.4
2             6.5
3            11.2
4            13.8
5             4.2
6             3.8
7            16.5
8             2.7
9            20.5
10            9.1
11           10.3
12            6.2
13            5.9
14           13.2
15           17.8
16            4.5
17            3.5
18           21.4
19            8.6

In [11]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

import joblib

In [12]:
le_fuel = LabelEncoder()
le_seller = LabelEncoder()
le_trans = LabelEncoder()

df["Fuel_Type"] = le_fuel.fit_transform(df["Fuel_Type"])
df["Seller_Type"] = le_seller.fit_transform(df["Seller_Type"])
df["Transmission"] = le_trans.fit_transform(df["Transmission"])

In [13]:
X = df.drop("Selling_Price",axis=1)

y = df["Selling_Price"]

In [14]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [15]:
model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [16]:
y_pred = model.predict(X_test)

In [17]:
print("MAE :",mean_absolute_error(y_test,y_pred))
print("MSE :",mean_squared_error(y_test,y_pred))
print("R2 Score :",r2_score(y_test,y_pred))

MAE : 0.5497500000000004
MSE : 0.4937932500000025
R2 Score : 0.983747110736253

In [18]:
joblib.dump(model,"car_price_model.pkl")

['car_price_model.pkl']

In [19]:
joblib.dump(
    {
        "Fuel_Type":le_fuel,
        "Seller_Type":le_seller,
        "Transmission":le_trans
    },
    "label_encoders.pkl"
)

['label_encoders.pkl']

In [22]:
model = joblib.load("car_price_model.pkl")

encoders = joblib.load("label_encoders.pkl")

year = int(input("Enter Year : "))
present_price = float(input("Enter Present Price : "))
kms = int(input("Enter Kms Driven : "))

fuel = input("Fuel Type (Petrol/Diesel): ")
seller = input("Seller Type (Dealer/Individual): ")
trans = input("Transmission (Manual/Automatic): ")

owner = int(input("Owner : "))

fuel = encoders["Fuel_Type"].transform([fuel])[0]
seller = encoders["Seller_Type"].transform([seller])[0]
trans = encoders["Transmission"].transform([trans])[0]

user_data = [[
    year,
    present_price,
    kms,
    fuel,
    seller,
    trans,
    owner
]]

prediction = model.predict(user_data)

print("\nPredicted Car Price")
print("₹",round(prediction[0],2),"Lakhs")

Enter Year : 2028
Enter Present Price : 11.4
Enter Kms Driven : 2000
Fuel Type (Petrol/Diesel): Petrol
Seller Type (Dealer/Individual): Dealer
Transmission (Manual/Automatic): Manual
Owner : 1

Predicted Car Price
₹ 16.6 Lakhs

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(